masters:
jump_server:
  hosts:
    master-01:
      ansible_host: 192.168.1.110
    master-02:
      ansible_host: 192.168.1.111
    master-03:
      ansible_host: 192.168.1.112
slaves:
  hosts:
    slave-01:
      ansible_host: 192.168.1.113
    slave-02:
      ansible_host: 192.168.1.114
nfs_servers:
  hosts:
    server-01 :
      ansible_host: 192.168.1.115
# control-node:
      ansible_host: 184.73.57.192
control-node:
   hosts:
     master-01:
       ansible_host: 192.168.1.110
#   hosts:
#     master-01:
#       ansible_host: 192.168.1.110
