masters:
  hosts:
    master1:
      ansible_host: 192.168.1.110
    master2:
      ansible_host: 192.168.1.111
    master3:
      ansible_host: 192.168.1.112
slaves:
  hosts:
    slavea:
      ansible_host: 192.168.1.113
    slaveb:
      ansible_host: 192.168.1.114