- name: Create a volume
  community.docker.docker_volume:
    name: caddy_data
- name: Install custom caddy container
  community.docker.docker_container:
    name: proxy
    image: ghcr.io/nfl-nzr/caddyflare:v0.1.1
    state: started
    restart: true
    restart_policy: "unless-stopped"
    env:
      DOMAIN: "*.nfl-nzr.com"
      CF_API_TOKEN: "{{ cloudflare_token }}"
      PROXY_ADDR: "{{ jump_server_proxy_addr | default(10.12.12.2) }}"
    volumes:
      - caddy_data:/data
    ports:
      - "80:80"
      - "443:443"
      - "2019:2019"
