# k3s master bootstrapping
- name: Create k3s master node
  ansible.builtin.command: "sh k3s.sh --tls-san={{tls_san_addr}} --disable=servicelb"
  become: true
  args:
    chdir: "{{k3s_install_script_path}}"
  environment: 
    K3S_CLUSTER_INIT: "true"
    K3S_TOKEN: "{{k3s_join_token}}"
  when: ansible_hostname == "master-01"
- name: Add nodes to main master
  ansible.builtin.command: "sh k3s.sh --tls-san={{tls_san_addr}} --disable=servicelb --server=https://{{hostvars[groups['masters'][0]].ansible_host}}:6443 --token={{k3s_join_token}}"
  become: true
  args:
    chdir: "{{k3s_install_script_path}}"
  environment: 
    K3S_TOKEN: "{{k3s_join_token}}"
  when: ansible_hostname != "master-01"
- name: Install kube-vip-cloud-controller for load balancer.
  become: true
  ansible.builtin.command: kubectl apply -f https://raw.githubusercontent.com/kube-vip/kube-vip-cloud-provider/main/manifest/kube-vip-cloud-controller.yaml
- name: Copy kube-vip configmap
  ansible.builtin.copy:
    src: kv-configmap-patch.yml
    dest: "{{ansible_env.HOME}}/kv-configmap-patch.yml"