- name: Configure k3s ingress
  tags:
    - k3s
    - k3s-master
  become: true
  ansible.builtin.command: "kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-{{ k3s_storage_ver | default('1.6.0') }}/deploy/static/provider/cloud/deploy.yaml"