# TODO cleanup tags 
- name: Preinstall
  tags:
    - preinstall, misc
  hosts: all
  gather_facts: true
  vars:
  roles:
    - preinstall
    - k3s_init
- name: Configure master nodes
  tags: 
    - master
  hosts: masters
  gather_facts: true
  vars:
    k3s_install_script_path: "{{ansible_env.HOME}}/k3s_install_script"
  roles:
   - k3s_master
- name: Configure slave nodes
  tags:
    - slave
  hosts: slaves
  gather_facts: true
  vars:
    k3s_install_script_path: "{{ansible_env.HOME}}/k3s_install_script"
  roles:
   - k3s_slave
- name: Configure load balancer
  tags:
    - lb, ing, k3s, master, slave
  hosts: 
    - control-node
  gather_facts: true
  roles:
   - k3s_ingress
   - k3s_loadbalancer
   - k3s_storage
- name: Postinstall
  tags:
    - misc, postinstall
  hosts: 
    - control-node
  gather_facts: true
  roles:
   - postinstall
- name: Configure NFS servers
  tags:
    - nfs
  hosts: nfs_servers
  gather_facts: true
  roles:
    - nfs-server